# Generated by Django 5.1.1 on 2024-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('predicted_rating', models.IntegerField(blank=True, null=True, verbose_name='Предсказанный рейтинг')),
                ('predicted_sentiment', models.CharField(blank=True, max_length=10, null=True, verbose_name='Статус отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
